DROP TABLE IF EXISTS `demo`.`post`;
DROP TABLE IF EXISTS `demo`.`user`;

CREATE TABLE IF NOT EXISTS `demo`.`user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_login_at` TIMESTAMP NULL,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` BINARY(60) NOT NULL,
  `display_name` VARCHAR(45) NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));

CREATE TABLE IF NOT EXISTS `demo`.`post` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(255) NOT NULL,
  `markdown` TEXT NOT NULL,
  `html` TEXT NOT NULL,
  `status` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user`
  FOREIGN KEY (`user_id`)
  REFERENCES `demo`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);